# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Je We eL
email: janwillem.luiten@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a blog about software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jwluiten.github.io" # the base hostname & protocol for your site
twitter_username: janwillemluiten
github_username:  jwluiten

# Build settings
markdown: kramdown
